comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: true

coverage:
  status:
    project:
      default:
        target: auto
    patch:
      default:
        target: auto

ignore:
  - "src/ere/models/core.py"
  - "test/**"
