[project]
name = "ers-core"
version = "0.0.1"
description = """
  The core components for the Entity Resolution System (ERS) components.
  
  The ERS is a pluggable entity resolution system for data transformation pipelines.
"""

authors = [
    {name = "Meaningfy", email = "hi@meaningfy.ws"}
]

readme = "README.md"
requires-python = "^3.14"

[tool.poetry.dependencies]
python = "^3.14"
pydantic = ">=2.10.6,<3.0.0"

[dependency-groups]
dev = [
    "linkml (>=1.9.2,<2.0.0)",
    "ruff (>=0.15.0,<0.16.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
# Needed when the root doesn't contain $project_name
packages = [
  { include = "*", from = "src" }
]
